### PR TITLE
Log exceptions

### LINKED ISSUE #22: Add better logging support
When running graphite-api with an application server (i.e. gunicorn) and hitting a 500 error the traceback, or at least the error message, should be logged to ease troubleshot the issue.
For example, if we forget to specify a unit into the ``from`` parameter:
```bash
$ curl 'http://127.0.0.1:2005/render?target=carbon.agents.*.errors&from=-600&format=json'
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```
PS: a picky user will also remark that the response is HTML instead of JSON ;)

### PR DESCRIPTION
**Pull request by cybem**
Fixes #22

### CODE REVIEW

**Comment by brutasse** [comment]
Actually since https://github.com/brutasse/graphite-api/commit/dfa272e0be3e4d7d58b2cf5d006a012e9aa4f988 exceptions should already be logged. Is any of you using a custom logging configuration? If so, can I see it?

**Comment by jtyr** [comment]
There is still missing the stacktrace patch from @Dieterbe . @Dieterbe please could you create a PR for that?

**Comment by brutasse** [comment]
Actually just passing `exc_info=True` to the `logger.error` call is enough.

@jtyr can I have your logging config? I see exceptions properly logged **without** this patch applied.

**Comment by jtyr** [comment]
I'm using this patch for logging:

```
diff -u -r ./a/graphite_api/config.py ./b/graphite_api/config.py
--- ./a/graphite_api/config.py	2014-12-04 02:15:52.000000000 -0600
+++ ./b/graphite_api/config.py	2015-01-06 09:46:44.690078253 -0600
@@ -1,8 +1,10 @@
 import logging
 import os
 import structlog
+import sys
 import warnings
 import yaml
+import traceback
 
 from tzlocal import get_localzone
 from importlib import import_module
@@ -13,6 +15,7 @@
 from .search import IndexSearcher
 from .storage import Store
 from . import DEBUG
+from flask.signals import got_request_exception
 
 try:
     from logging.config import dictConfig
@@ -73,6 +76,13 @@
     return getattr(finder, klass)
 
 
+def log_exception(sender, exception, **extra):
+    logger.error('Exception', exception=exception)
+    exc_info = sys.exc_info()
+    tb = traceback.format_exception(*exc_info)
+    for line in tb:
+        logger.error(line)
+
 def configure(app):
     config_file = os.environ.get('GRAPHITE_API_CONFIG',
                                  '/etc/graphite-api.yaml')
@@ -87,6 +97,8 @@
 
     configure_logging(config)
 
+    got_request_exception.connect(log_exception, app)
+
     for key, value in list(default_conf.items()):
         config.setdefault(key, value)
 
diff -u -r ./a/setup.py ./b/setup.py
--- ./a/setup.py	2014-12-04 02:15:52.000000000 -0600
+++ ./b/setup.py	2015-01-06 09:45:40.219074840 -0600
@@ -12,6 +12,7 @@
     'six',
     'structlog',
     'tzlocal',
+    'blinker',
 ]
 
 if sys.version_info < (2, 7):
```

Apart of this patch, I'm using no extra logging setting.

**Comment by brutasse** [comment]
I just reverted the merge. From a clean install from master, I'd be interested to see a case where exceptions are not logged.

**Comment by cybem** [comment]
I think you have confused _exceptions_ and their _stacktraces_. My PR adds logging _exceptions_, and  @Dieterbe's PR adds logging _exceptions with stacktraces_.

**Comment by brutasse** [comment]
No, I am already seeing exceptions *with stacktraces* in my logs. This has been the case since https://github.com/brutasse/graphite-api/commit/dfa272e0be3e4d7d58b2cf5d006a012e9aa4f988.

**Comment by jtyr** [comment]
Well, I did not see any exceptions in the log (stdout from gunicorn) without the patch I sent above when I was testing it like 2 months ago. So I'm sure the functionality provided by the commit dfa272e did not work for me.

**Comment by brutasse** [comment]
The issue is, I'm unable to reproduce a setup that hides exceptions… I'd love to see this issue happen in a reproduceable way.

**Comment by jtyr** [comment]
If you want to make the exception logging optional, you should allow to set the logging level. The exceptions are logged only in the "error" log level. Or change the log level for exception to "critical".

**Comment by Dieterbe** [comment]
@brutasse can you share your config? i've been trying various config settings (debug vs warn, propagate true vs false, disable_existing_loggers true/false, version 1 or removing the line, with and without sentry_dsn line, templates/cache/statsd settings on/of, etc) and every time i request `/render?width=aoeu&target=foo` i get an http 500 but no exception in log (stdout)
in fact nothing appears in the log :(

i run like so:
`
gunicorn -b 0.0.0.0:8000 -w 24 --log-level debug graphite_api.app:app`
```
root@e85f1b2d1687:~# cat /etc/graphite-api.yaml 
search_index: /srv/graphite/index
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions

whisper:
  directories:
    - /srv/graphite/whisper
time_zone: America/New_York
logging:
  handlers:
    file:
      class: logging.FileHandler
      filename: /var/log/graphite-api.log
    stdout:
      class: logging.StreamHandler
  loggers:
    graphite_api:
      handlers:
        - stdout
      propagate: false
      level: DEBUG
    root:
      handlers:
        - stdout
      propagate: false
      level: DEBUG
```

**Comment by Dieterbe** [comment]
since Bruno commented higher up ` Is any of you using a custom logging configuration? If so, can I see it?` i took out all logging config, and have it like:
```
search_index: /srv/graphite/index
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions

whisper:
  directories:
    - /srv/graphite/whisper
time_zone: America/New_York
```
same result, http 500 but no exception

**Comment by jtyr** [comment]
I run gunicorn like this:

```
gunicorn graphite_api.app:app -b ${BIND_ADDRESS:-127.0.0.1}:${PORT:-8888} $GUNICORN_OPTIONS 1>/var/log/$NAME.log 2>&1 &
```

So basically redirect the STDOUT/STDERR into a file.

And my `graphite-api.yaml` looks like this:

```
allowed_origins:
  - "*"
cache:
  dir: "/tmp/graphite-api-cache"
  type: "filesystem"
finders:
  - "graphite_influxdb.InfluxdbFinder"
functions:
  - "graphite_api.functions.SeriesFunctions"
  - "graphite_api.functions.PieFunctions"
influxdb:
  db: "graphite"
  host: "192.168.56.104"
  pass: "root"
  port: 8086
  schema:
    -
      - ""
      - 10
    -
      - "high-res-metrics"
      - 1
  user: "root"
search_index: "/var/lib/graphite-api/index"
time_zone: "US/Central"
```

**Comment by jtyr** [comment]
Any further comments on this issue? Any example how to setup logging which would show exceptions with stacktrace? It only works for me when using the above patch (https://github.com/brutasse/graphite-api/pull/73#issuecomment-74080310).

**Pull request merged**
